Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -4,17 +4,27 @@ phases:
   install:
     runtime-versions:
       docker: 20
+    commands:
+      - echo Installing AWS CLI and Docker
+      - aws --version
+      - docker --version
   pre_build:
     commands:
       - echo Logging in to Amazon ECR...
-      - aws --version
-      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
+      - echo "Region: $AWS_DEFAULT_REGION"
+      - echo "ECR URI: $ECR_REPOSITORY_URI"
+      - |
+        if ! aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI; then
+          echo 'Docker login failed'
+          exit 1
+        fi
       - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-9)
       - IMAGE_TAG=${COMMIT_HASH:=app}
       - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
       - IMAGE_TAG1=${COMMIT_HASH:=resque}
   build:
     commands:
+      - echo Downloading secrets from S3...
       - aws s3 cp s3://trooptrack-ble/master.key ./config/master.key
       - aws s3 cp s3://trooptrack-ble/youthraise-cicd/production.key ./config/credentials/production.key
       - echo Build started on `date`
@@ -26,11 +36,27 @@ phases:
   post_build:
     commands:
       - echo Build completed on `date`
-      - echo Pushing Docker images...
-      - docker push $ECR_REPOSITORY_URI:app
-      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
-      - docker push $ECR_REPOSITORY_URI:resque
-      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG1
+      - echo Pushing Docker images to ECR...
+      - |
+        if ! docker push $ECR_REPOSITORY_URI:app; then
+          echo 'Docker push for app failed'
+          exit 1
+        fi
+      - |
+        if ! docker push $ECR_REPOSITORY_URI:$IMAGE_TAG; then
+          echo 'Docker push for app with tag failed'
+          exit 1
+        fi
+      - |
+        if ! docker push $ECR_REPOSITORY_URI:resque; then
+          echo 'Docker push for resque failed'
+          exit 1
+        fi
+      - |
+        if ! docker push $ECR_REPOSITORY_URI:$IMAGE_TAG1; then
+          echo 'Docker push for resque with tag failed'
+          exit 1
+        fi
       - printf '{"ImageURI":"%s:%s"}' $ECR_REPOSITORY_URI $IMAGE_TAG > imageDetail.json
       - printf '{"ImageURI1":"%s:%s"}' $ECR_REPOSITORY_URI $IMAGE_TAG1 > imageDetail1.json
 
